name: Volume Spike Check

on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch:   # Allows manual trigger

jobs:
  check-volume:
    runs-on: ubuntu-latest
    env:
      OANDA_API_KEY: ${{ secrets.OANDA_API_KEY }}
      OANDA_ACCOUNT_ID: ${{ secrets.OANDA_ACCOUNT_ID }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run volume check
        run: python volume_alert.py | tee run.log

      - name: Upload run log
        uses: actions/upload-artifact@v4
        with:
          name: run-log
          path: run.log
